### ISSUE TITLE
DeepGram shows black transcription for video longer than an hour.

### ISSUE THREAD

**Issue by holanino** [Marksdo/Whisper#12]
For some reason when selecting DeepGram Whisper it show a transcription when finished for videos longer than an hour. It does not work with Whisper either medium or large models, none of the models work.

Also it says "No Logs. Please Start Process Task First (Old Project Before V5.0 No Logs)"

I do not know what is going on. It does work with DeepGram Enhanced and with videos shorter than one hour. 

(I cant add screenshots here for some reason, tried two browsers, GitHub having trouble?)

**Comment by Marksdo** [comment]
I just test an video longer than 1 hour, It can get the result from deepgram. 

Can you send me the file that you can't transcribe with deepgram api? If it fail then i will debug to see what is happen. Cause i test all file before is always ok. The response is always success. So i need an example file that fail and i will get the error response to display.

---
"No Logs. Please Start Process Task First (Old Project Before V5.0 No Logs)" This log is show in using local whisper model process when use deepgram remote transcribe there is no log details

**Comment by Marksdo** [comment]
Test another 2 hours video. It also can be transcribe with deepgram. Can you see me the file you can't transcribe to test and let me track the issue?
<img width="879" alt="image" src="https://github.com/Marksdo/Whisper/assets/117704549/259ea49a-e39a-4ea5-9cf7-0835d935b97a">

**Comment by holanino** [comment]
This is a link to a video that will not work in Whisper Mate. The result is empty/blank

https://www.youtube.com/watch?v=DQhNHo6Ioa8

You can use this to download - https://ssyoutube.com/

Try and if not I can let you use my api key. I try in Whisper Mate 5.4.3 and .5.4.4 does not work.

I cut video in half and part 1 worked and part 2 worked also.

**Comment by Marksdo** [comment]
I use Whisper Mate embed download video plugin to download and transcribe with Deepgram is success.(Maybe you download with ssyoutube.com's file is something wrong?
<img width="1270" alt="image" src="https://github.com/Marksdo/Whisper/assets/117704549/7ed82194-833c-485f-8fcf-145784bca6a3">

BTW:
Whisper Mate self has an plugin download video from website, just enable it in settings. It can direct download media from well-known video website.
<img width="1019" alt="image" src="https://github.com/Marksdo/Whisper/assets/117704549/edfae2ff-b012-4bbc-9a18-2c06f71565c5">
<img width="1121" alt="image" src="https://github.com/Marksdo/Whisper/assets/117704549/12e850e1-d57c-4b75-bc92-472f4754b07a">

**Comment by Marksdo** [comment]
Preference > Plugin > Download
Remember to set an download folder first. Cause Whisper Mate is run in Sandbox mode. It need you give permission first.

<img width="700" alt="202311-22-2" src="https://github.com/Marksdo/Whisper/assets/117704549/18124131-492f-469a-b409-d5f280f118fb">

> For reply to upload image. I meet your previous issue, can't upload image to github with chrome. I switch to safari. it can upload now.

**Comment by Marksdo** [comment]
Tips: 
When enable the download plugin. You also can paste url direct to Whisper Mate when it is in front. No need to click the main toolbar add url button. 😀

**Comment by holanino** [comment]
Thank you very much for your time. It was a video incompatibility. 🙏

**Comment by Marksdo** [comment]
Hi, sorry i just see your response. Can you send me the downloaded livestream file?

I found that some issue report to can't get audio from video ( So maybe some file like this, I think maybe livestream that make media file's timestamp is mismatch ), It can be auto fix it by WhisperMate. So i need an example to verify this is real fix. 
Can you send the url or file to me?

**Comment by holanino** [comment]
It is doing it again, but not sure why. When I upload a video to be transcribed by Deepgram it will not work. Videos over 30 minutes it does not work, if under 15 minutes, it works.

I paste video link in Whisper Mate and choose audio mp4, mp3 it does not work. Empty transcription.

Example Video:

https://www.youtube.com/watch?v=sv3-A1H-hes

<img width="338" alt="Screenshot 2024-01-18 at 7 59 59 PM" src="https://github.com/Marksdo/Whisper/assets/11935461/5f8b50d3-1a8a-4c7f-83da-1666cb79321e">

**Comment by holanino** [comment]
Looks like Whisper Cloud has 20 minute limit now?

https://developers.deepgram.com/docs/deepgram-whisper-cloud

**Comment by Marksdo** [comment]
According to the Deepgram document, it is likely that one file processing time is limited. You can try splitting the file into multiple projects(Use Whisper Mate Quick Cut) to see it's work?


https://developers.deepgram.com/docs/getting-started-with-pre-recorded-audio#maximum-processing-time
---
# Maximum Processing Time
Nova, Base, and Enhanced provide extremely fast transcription. Deepgram limits the maximum processing time to 10 minutes for these models.

Whisper is much slower than the other models, and the maximum processing time is 20 minutes for Whisper.

If a request takes longer than the maximum processing time to complete, the request is cancelled and a 504: Gateway Timeout error is returned.

**Comment by holanino** [comment]
The reason I use DeepGram Whisper is because is does not group subtitles
into paragraphs/groups of words as much as Local computer Whisper.

I wish Whaisper Mate local app would make subtitles based on time matching
the timing spoken with the speaker.

Current Whisper Model medium and Large groups words into group of words and
then there is empty/silence even though the speaker is still speaking.

There are no pauses to match the timing of the speaker.

**Comment by Marksdo** [comment]
It seem that DeepGram has do some pre-processing of the audio

I think it may be first turn audio to chunks split by speaker then do the transcribe.

**Comment by holanino** [comment]
Can we get Nova2 as an option. The app only has Nova (1)

**Comment by Marksdo** [comment]
Thanks for info it, Will add to V5.5.0

**Comment by holanino** [comment]
Thank you
