### ISSUE TITLE
是否有教育优惠？

### ISSUE THREAD

**Issue by Lettte** [Marksdo/Whisper#14]
rt

**Comment by Marksdo** [comment]
后台设置是允许教育优惠的,但需要通过Apple School Manager购买20个才可以

另外由于国区现在限制人工智能相关的App上线,国区无法下载Whisper Mate,请从 https://whisper.marksdo.com 下载Uni版本 (Uni版本同样是运行在沙箱安全模式并通过苹果验证的,只是支付走的是Gumroad的渠道),

Gumroad优惠券可以有教育优惠.请单独发送信息到 imarksdo@gmail.com,我将发送相关的学生优惠让您在Gumroad上支付时兑换.感谢支持


--- copy from app store pricing config page
You can offer a 50% discount to educational institutions when they purchase 20 or more copies of your iOS or macOS app through Apple School Manager
