### ISSUE TITLE
5.5.0 Crashes before finishing transcription

### ISSUE THREAD

**Issue by holanino** [Marksdo/Whisper#21]
5.5.0 Crashes before finishing transcription using Whisper models.

Also why can I not use previous versions of Whisper Mate. I have a back up copy of Whisper Mate 5.4.9 and it crashes when I open it.

We should be able to use previous versions. Any idea why I cannot. Should I delete preferences or is it something in the app that you limit from using previous Whisper Mate app versions?

<img width="312" alt="Screenshot 2024-02-05 at 7 36 31 PM" src="https://github.com/Marksdo/Whisper/assets/11935461/daf3bbeb-b9a2-4586-a1d4-1262c3b7c6e2">

**Comment by Marksdo** [comment]
do you enable any automation option? it seem that stop on invoke the automation steps.

restore to previous version also need to use the previous database file. case database file can't auto downgrade

**Comment by holanino** [comment]
No automation. I run this test and it crashes. I try different models. Deep Gram works but not local Whisper.

<img width="309" alt="Screenshot 2024-02-05 at 9 22 10 PM" src="https://github.com/Marksdo/Whisper/assets/11935461/652a8e1d-a4ea-4eaa-b714-db424f0d6eca">

How can I run previous versions of app. I have it back up but crashes when open.

**Comment by Marksdo** [comment]
Please note that the following shell script will delete your related configuration and data information in Whipser Mate.

```
defaults delete com.marksdo.WhisperMate
rm -frv /Users/"Replace this to your account name"/Library/Containers/com.marksdo.WhisperMate
```

And Re-run the V5.4.9, the database file will use the init data

**Comment by holanino** [comment]
Thank you, problem resolved.

**Comment by holanino** [comment]
Thank you, problem resolved.
