### ISSUE TITLE
??? now the app is asking for pro version for pay.. 

### ISSUE THREAD

**Issue by wqwe2** [Marksdo/Whisper#25]
??? now the app is asking for pro version for pay.. and there is now such upgrade option. now I am stuck.. turning it to pay app. what a dissapointment.

**Comment by wqwe2** [comment]
ok my bad I have just purchased this app. and I am facing another issue at the moment..

**Comment by Marksdo** [comment]
what issue?

**Comment by wqwe2** [comment]
I have raised new issue with screenshot please see the latest post. and thank you for the quick reply
